from selenium.webdriver import Chrome
import time
driver=Chrome()
driver.get("https://www.makemytrip.com/")
driver.maximize_window()
c=driver.find_element_by_xpath("//span[@class='commonModal__close']")
c.click()
from_element=driver.find_element_by_xpath("//input[@value='Delhi']")
from_element.send_keys('Bengaluru')
to_element=driver.find_element_by_xpath("//input[@id='toCity']")
to_element.send_keys("Mumbai")
departure=driver.find_element_by_xpath("//p[@data-cy='departureDate']")
departure.click()
date=driver.find_element_by_xpath("//div[@aria-label='Mon Jun 10 2024']")
date.click()
search=driver.find_element_by_xpath("//a[contains(text(),'Search')]")
search.click()
time.sleep(95)
# c2=driver.find_element_by_xpath("//span[@class='bgProperties  overlayCrossIcon icon20']")
# time.sleep(2)
driver.close()